POST http://localhost:3000/register/
Content-Type: application/json

{
  "username": "Ram",
  "name": "ram",
  "email":"ram@gmail.com",
  "password": "ram22",
  "gender": "male",
  "location": "Hyderabad",
  "mobileNumber":"1234567890"
} 


###

POST http://localhost:3000/login/
Content-Type: application/json

{
  "email": "ram@gmail.com",
  "password": "ram22"
}

### 

Get http://localhost:3000/Profile/
Content-Type: application/json