POST http://localhost:5000/register/
Content-Type: application/json

{
  "username": "Ramu",
  "name": "ramu",
  "email":"ramu@gmail.com",
  "password": "ramu22",
  "gender": "male",
  "location": "Hyderabad"
} 

###

POST http://localhost:5000/login/
Content-Type: application/json

{
  "username": "gopal",
  "password": "gopal22"
}

### 

Get http://localhost:5000/Profile/
Content-Type: application/json